// -----------------------------------------------------------------------------
// Grafana provisioning files, written by the integration in /data.
//
// The manifest mounts two volumes in the Grafana sub-container; the supervisor
// derives their host folders from /data, so the integration sees them as:
//
//   /data/containers/grafana/etc/grafana/provisioning  -> /etc/grafana/provisioning
//   /data/containers/grafana/var/lib/grafana           -> /var/lib/grafana
//
// Grafana reads at startup:
//   datasources/gladys.yaml   the "Gladys" Prometheus data source, pointing
//                             at the API served by this integration;
//   dashboards/gladys.yaml    the dashboards provider (folder "Gladys"),
//   dashboards/gladys/*.json  re-read every 30 s, so a regenerated overview
//                             shows up without restarting Grafana.
// -----------------------------------------------------------------------------

import { randomBytes } from 'node:crypto';
import { chmod, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { DATASOURCE, buildDeviceDashboard, buildOverviewDashboard } from './dashboards.js';

export const CONTAINER_NAME = 'grafana';
export const GRAFANA_PORT = 3000;
// Paths INSIDE the Grafana container.
export const PROVISIONING_MOUNT = '/etc/grafana/provisioning';
export const GRAFANA_DATA_MOUNT = '/var/lib/grafana';
export const DATASOURCE_USER = 'grafana';

export function paths(dataDir) {
  const root = path.join(dataDir, 'containers', CONTAINER_NAME);
  const provisioning = path.join(root, PROVISIONING_MOUNT);
  return {
    provisioning,
    grafanaData: path.join(root, GRAFANA_DATA_MOUNT),
    datasources: path.join(provisioning, 'datasources'),
    dashboardProviders: path.join(provisioning, 'dashboards'),
    dashboards: path.join(provisioning, 'dashboards', 'gladys'),
    secrets: path.join(provisioning, 'secrets'),
    datasourceSecret: path.join(dataDir, 'datasource-secret'),
  };
}

// JSON strings are valid YAML double-quoted scalars: no YAML library needed.
const q = (value) => JSON.stringify(String(value));

export function datasourceYaml({ url, password }) {
  return `# Generated by the Gladys Grafana integration: changes are overwritten.
apiVersion: 1
datasources:
  - name: Gladys
    uid: ${q(DATASOURCE.uid)}
    type: ${q(DATASOURCE.type)}
    access: proxy
    url: ${q(url)}
    isDefault: true
    editable: false
    basicAuth: true
    basicAuthUser: ${q(DATASOURCE_USER)}
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.50.0
      timeInterval: 1m
      disableRecordingRules: true
      manageAlerts: false
    secureJsonData:
      basicAuthPassword: ${q(password)}
`;
}

export function dashboardProviderYaml() {
  return `# Generated by the Gladys Grafana integration: changes are overwritten.
apiVersion: 1
providers:
  - name: gladys
    orgId: 1
    folder: Gladys
    folderUid: gladys
    type: file
    disableDeletion: false
    allowUiUpdates: false
    updateIntervalSeconds: 30
    options:
      path: ${q(`${PROVISIONING_MOUNT}/dashboards/gladys`)}
`;
}

/** Secret shared by the data source and our API, created once. */
export async function datasourcePassword(dataDir) {
  const file = paths(dataDir).datasourceSecret;
  try {
    const existing = (await readFile(file, 'utf8')).trim();
    if (existing) return existing;
  } catch {
    // first run
  }
  const secret = randomBytes(24).toString('hex');
  await mkdir(dataDir, { recursive: true });
  await writeFile(file, secret, { mode: 0o600 });
  return secret;
}

async function writeIfChanged(file, content, mode = 0o644) {
  try {
    if ((await readFile(file, 'utf8')) === content) return false;
  } catch {
    // missing file
  }
  await writeFile(file, content, { mode });
  // writeFile keeps the mode of an existing file: force it.
  await chmod(file, mode);
  return true;
}

/**
 * Prepare the folders of both volumes. Grafana runs as uid 472 while this
 * container runs as uid 1000: its data folder is opened to every user (it
 * only exists inside the integration folder, readable by root only).
 */
export async function prepareFolders(dataDir) {
  const p = paths(dataDir);
  for (const dir of [p.datasources, p.dashboards, p.secrets, p.grafanaData]) {
    await mkdir(dir, { recursive: true });
  }
  for (const sub of ['plugins', 'alerting', 'notifiers']) {
    await mkdir(path.join(p.provisioning, sub), { recursive: true });
  }
  await chmod(p.grafanaData, 0o777);
}

/**
 * Write the files Grafana reads at startup. Returns true when one of them
 * changed, i.e. when a running Grafana must be restarted to see it.
 */
export async function writeStartupFiles(
  dataDir,
  { datasourceUrl, datasourcePassword, adminPassword },
) {
  const p = paths(dataDir);
  const changes = await Promise.all([
    writeIfChanged(
      path.join(p.datasources, 'gladys.yaml'),
      datasourceYaml({ url: datasourceUrl, password: datasourcePassword }),
    ),
    writeIfChanged(path.join(p.dashboardProviders, 'gladys.yaml'), dashboardProviderYaml()),
  ]);
  // Read through GF_SECURITY_ADMIN_PASSWORD__FILE: the password never goes
  // through the container env (stored by Gladys) nor the public manifest.
  // Grafana applies it when it creates its database only; later changes are
  // applied through its API (see container.js).
  await writeIfChanged(path.join(p.secrets, 'admin_password'), adminPassword);
  return changes.some(Boolean);
}

/**
 * Write (or remove) the Gladys dashboards. Grafana re-reads the folder every
 * 30 s. Returns true when a file changed.
 */
export async function writeDashboards(dataDir, series, { enabled }) {
  const { dashboards } = paths(dataDir);
  if (!enabled) {
    const existing = await readdir(dashboards).catch(() => []);
    await Promise.all(existing.map((file) => rm(path.join(dashboards, file), { force: true })));
    return existing.length > 0;
  }
  await mkdir(dashboards, { recursive: true });
  const changes = await Promise.all([
    writeIfChanged(
      path.join(dashboards, 'overview.json'),
      `${JSON.stringify(buildOverviewDashboard(series), null, 2)}\n`,
    ),
    writeIfChanged(
      path.join(dashboards, 'device.json'),
      `${JSON.stringify(buildDeviceDashboard(), null, 2)}\n`,
    ),
  ]);
  return changes.some(Boolean);
}
